# Site settings
title: 98team
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  98team blog is a website for people who want a text based tutorial.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Possyeater

# Build settings
markdown: kramdown
